### ISSUE TITLE
EMA Normalization

### ISSUE THREAD

**Issue by eugenelawrence** [XiaLiPKU/EMANet#1]
In 6.2.1, it says that 'From the right part of Fig. 3, it is clear to see that LN is better than no normalization'. But in the right part of Fig. 3, it seems that no normalization is better than LN. Is the figure wrong?
![image](https://user-images.githubusercontent.com/15603290/62289583-a7347000-b491-11e9-8157-fe69239d3de8.png)

**Comment by XiaLiPKU** [comment]
This was really a mistake, as I meant to "no better than". I will fix it. Thank you very much！
