### ISSUE TITLE
分割结果边缘呈锯齿状

### ISSUE THREAD

**Issue by whuhit** [XiaLiPKU/EMANet#10]
在使用EMANet跑VOC数据集和自己的数据集，最后的分割边缘都有明显的锯齿状，请问你们的结果也是这样的吗？

**Comment by initbin** [comment]
请问训练时，latest.pth是在哪里获得吗？谢谢。我训练时
error:
ERROR - No checkpoint ./models/latest.pth!

**Comment by whuhit** [comment]
> 请问训练时，latest.pth是在哪里获得吗？谢谢。我训练时
> error:
> ERROR - No checkpoint ./models/latest.pth!

这个不用管，代码没错的话，接下来就开始模型训练了。这个文件会生成的

**Comment by wwq66** [comment]
想问下你最终测试时mIoU能达到多少？我在自己的数据集上训练后mIoU只有不到0.4

**Comment by initbin** [comment]
> > 请问训练时，latest.pth是在哪里获得吗？谢谢。我训练时
> > error:
> > ERROR - No checkpoint ./models/latest.pth!
> 
> 这个不用管，代码没错的话，接下来就开始模型训练了。这个文件会生成的

谢谢，我的是单个GPU, 代码有点问题。

**Comment by whuhit** [comment]
> 想问下你最终测试时mIoU能达到多少？我在自己的数据集上训练后mIoU只有不到0.4

最终结果没有测试，不过应该挺高的，肯定不止0.4。

**Comment by XiaLiPKU** [comment]
> > > 请问训练时，latest.pth是在哪里获得吗？谢谢。我训练时
> > > error:
> > > ERROR - No checkpoint ./models/latest.pth!
> > 
> > 
> > 这个不用管，代码没错的话，接下来就开始模型训练了。这个文件会生成的
> 
> 谢谢，我的是单个GPU, 代码有点问题。

Of course, single GPU cannot reproduce it. The batch size is very important!
