### ISSUE TITLE
How can eval.py generate results of segmentation?

### ISSUE THREAD

**Issue by illutheplanet** [XiaLiPKU/EMANet#13]
When running eval.py only appears mIoU, what should I do to get the segmentation maps?

**Comment by XiaLiPKU** [comment]
> When running eval.py only appears mIoU, what should I do to get the segmentation maps?

I would like to add this function further.
For now, you can hack the codes, and save the 'pred' into a png.
Moreover, to visualize the results by eye, you may need colorize the generated pngs.

**Comment by robotcv** [comment]
how to show attention map?

**Comment by XiaLiPKU** [comment]
> how to show attention map?

Just output the Z is enough.
But for better color and value, you would better normalize the value map.

**Comment by robotcv** [comment]
> > how to show attention map?
> 
> Just output the Z is enough.
> But for better color and value, you would better normalize the value map.

**Comment by sdx2199** [comment]
Okay, thank you very much.

**Comment by robotcv** [comment]
> > > how to show attention map?
> > 
> > 
> > Just output the Z is enough.
> > But for better color and value, you would better normalize the value map.

Okay, thank you very much
