### ISSUE TITLE
Will  'mu'  be updated during evaluation?

### ISSUE THREAD

**Issue by baistbst** [XiaLiPKU/EMANet#15]
It seems that ’mu‘ will be updated during evaluation, in other worlds, it will record some information in test set? It's ok or should be banned?

**Comment by ngunauj** [comment]
will self.mu be update when training ?

**Comment by ngunauj** [comment]
> It seems that ’mu‘ will be updated during evaluation, in other worlds, it will record some information in test set? It's ok or should be banned?

will self.mu be update when training?
