### ISSUE TITLE
EMAU：mu = self._l2norm(mu, dim=1)，can i remove this? and just use kaiming normal?

### ISSUE THREAD

**Issue by ngunauj** [XiaLiPKU/EMANet#20]
https://github.com/XiaLiPKU/EMANet/blob/f7d7b4746104ea62bc5bd3186f6fcb8ea71e3579/network.py#L200

**Comment by ngunauj** [comment]
and will self.mu be updated?

**Comment by XiaLiPKU** [comment]
> https://github.com/XiaLiPKU/EMANet/blob/f7d7b4746104ea62bc5bd3186f6fcb8ea71e3579/network.py#L200

The function of this formula is stated in section 5.3.
And in Fig.3(2), you can the the normalization is important
