### ISSUE TITLE
Fail to reproduce your results on COCO-STUFF

### ISSUE THREAD

**Issue by zenght** [XiaLiPKU/EMANet#23]
Hi @XiaLiPKU ! Your work is amazing, and i am appreciate that you have released your code.
May i ask question? Based on your code, i have modified your code to suit COCO-STUFF training. But i can only get 34.55% miou. I just followed your default setting, but in single gpu. (  pretrained ResNet-101, batch size 3, 30k iterations and so on...).

Looking forward to your reply!
Best wishes

**Comment by XiaLiPKU** [comment]
> Hi @XiaLiPKU ! Your work is amazing, and i am appreciate that you have released your code.
> May i ask question? Based on your code, i have modified your code to suit COCO-STUFF training. But i can only get 34.55% miou. I just followed your default setting, but in single gpu. ( pretrained ResNet-101, batch size 3, 30k iterations and so on...).
> 
> Looking forward to your reply!
> Best wishes

Batch size is one of the most factor of segmentation's performance. In my experiment, the batch size is 16
