### ISSUE TITLE
Where is the pretrained model 'Resnet152'?

### ISSUE THREAD

**Issue by shipengai** [XiaLiPKU/EMANet#24]
Thanks for releasing the code.
Where is the pretrained model 'Resnet152'?
I am looking forward to your reply.

**Comment by XiaLiPKU** [comment]
> Thanks for releasing the code.
> Where is the pretrained model 'Resnet152'?
> I am looking forward to your reply.

I just borrow the models from the repo [pytroch-encoding](https://github.com/zhanghang1989/PyTorch-Encoding)
