### ISSUE TITLE
The difference between the code and the original paper.

### ISSUE THREAD

**Issue by zhouyuan888888** [XiaLiPKU/EMANet#31]
Hi, thank you for releasing the code for EMANet. I find a difference between the code and the paper.  The difference lies in the formulation of Equation 13 (in the paper). In the paper, the M step (bases reconstruct) is formulated as follows:
[image](https://user-images.githubusercontent.com/41813767/69915101-307ea200-1486-11ea-87c5-973779257ec9.png)
However, in the code, the M step is formulated as: 
mu = torch.bmm(x, z_)   
Actually， mu = torch.bmm(x, z_) is the weighted summation of X. However, Equation 13 (in the paper) is not the weighted summation of X. Anything wrong in the paper?

**Comment by zhouyuan888888** [comment]
In the paper, M step is formulated as:
[image](https://user-images.githubusercontent.com/41813767/69915296-6755b780-1488-11ea-9f9f-d1f828cdd842.png)
in which Znk denotes the n-th pixel in the K-th channel in Z (Attention map), Xn denotes the feature vector of the n-th pixel. Why uk is obtained from the multiplication between Znk (scalar) and Xn? 
Expect for your explanations. Thank you so much.

**Comment by ZERO-Lab-PKU** [comment]
> Hi, thank you for releasing the code for EMANet. I find a difference between the code and the paper. The difference lies in the formulation of Equation 13 (in the paper). In the paper, the M step (bases reconstruct) is formulated as follows:
> [image](https://user-images.githubusercontent.com/41813767/69915101-307ea200-1486-11ea-87c5-973779257ec9.png)
> However, in the code, the M step is formulated as:
> mu = torch.bmm(x, z_)
> Actually， mu = torch.bmm(x, z_) is the weighted summation of X. However, Equation 13 (in the paper) is not the weighted summation of X. Anything wrong in the paper?

To be honest, I forget the \sum in the nominator....
When I found that, the paper cannot be changed

**Comment by XiaLiPKU** [comment]
> Hi, thank you for releasing the code for EMANet. I find a difference between the code and the paper. The difference lies in the formulation of Equation 13 (in the paper). In the paper, the M step (bases reconstruct) is formulated as follows:
> [image](https://user-images.githubusercontent.com/41813767/69915101-307ea200-1486-11ea-87c5-973779257ec9.png)
> However, in the code, the M step is formulated as:
> mu = torch.bmm(x, z_)
> Actually， mu = torch.bmm(x, z_) is the weighted summation of X. However, Equation 13 (in the paper) is not the weighted summation of X. Anything wrong in the paper?

To be honest, I forgot the \sum symbol in the numerator...
When I found that, the deadline of the camera-ready version had gone...

**Comment by zhouyuan888888** [comment]
@XiaLiPKU hahaha....， thank you for your explanation.
