### ISSUE TITLE
How long does it take to train EMANet with a Resnet-101 backbone?

### ISSUE THREAD

**Issue by ghost** [XiaLiPKU/EMANet#35]
Hello,

Thank you for publishing the code to your excellent work.
I was wondering how long it takes to train the EMANet with a Resnet-101 backbone - both for when the number of input channels is 256 and 512? How many GPUs did you use to achieve this training time?

Thank you in advance :)

**Comment by XiaLiPKU** [comment]
> Hello,
> 
> Thank you for publishing the code to your excellent work.
> I was wondering how long it takes to train the EMANet with a Resnet-101 backbone - both for when the number of input channels is 256 and 512? How many GPUs did you use to achieve this training time?
> 
> Thank you in advance :)

It was a long time ago. Let me see, maybe around 8-10 hours over four 1080 Ti.

**Comment by ghost** [comment]
Thank you!
