### ISSUE TITLE
ResNet18 pretrained model

### ISSUE THREAD

**Issue by Mayy1994** [XiaLiPKU/EMANet#45]
Hi,

Thanks for providing the pre-trained ResNet50 and ResNet101 models.
Do you have the pre-trained ResNet18 model that replaces the first 7x7 Conv to three 3x3 Conv?
I have surfed it for a long time but unfortunately, I didn't find it. If you have saved this model, could you please share it with me? 
Many thanks in advance.

**Comment by XiaLiPKU** [comment]
Sorry, we have not used ResNet-18
