### ISSUE TITLE
Is this a bug or trick?  image = (image - settings.MEAN) / settings.MEAN

### ISSUE THREAD

**Issue by gasvn** [XiaLiPKU/EMANet#7]
https://github.com/XiaLiPKU/EMANet/blob/9a492d8aaad297e15eac044b3bb9583e63ffa3a3/dataset.py#L19

I support this line should be  
```
image = (image - settings.MEAN) / settings.STD.
```
Or is this line a trick?

**Comment by XiaLiPKU** [comment]
Oh, this is really a bug in the released code. I will fix it right now. Thanks!

**Comment by XiaLiPKU** [comment]
But it seems that this line doesn't influence the final performance so much. No matter what, thanks for your carefulness.
