### ISSUE TITLE
RuntimeError:  self.net.module.load_state_dict(obj['net'])  

### ISSUE THREAD

**Issue by taotaoyuhust** [XiaLiPKU/EMANet#9]
using the pretrained model throw out this error: 
 
RuntimeError: Error(s) in loading state_dict for EMANet:
	Missing key(s) in state_dict: "extractor.4.0.conv1.weight", "extractor.4.0.bn1.weight", "extractor.4.0.bn1.bias", "extractor.4.0.bn1.running_mean", "extractor.4.0.bn1.running_var", "extractor.4.0.conv2.weight",       ...... 
	Unexpected key(s) in state_dict: "layer1.0.0.conv1.weight", "layer1.0.0.bn1.weight", "layer1.0.0.b

someone can help?

**Comment by XiaLiPKU** [comment]
Sorry, I forgot to change the keys' names

**Comment by taotaoyuhust** [comment]
3x for reply, so how to solve it?

**Comment by XiaLiPKU** [comment]
I will upload a usable pth sooner.

**Comment by shiyuanyin** [comment]
@XiaLiPKU ，
hello author,
Thank you for your work, I want to ask you a question ,your EMAnet is used segment, if I am use in  classification task .What do you think of the effect?     If it is necessary to try , the emau structure need to change?

**Comment by illutheplanet** [comment]
same problem here

**Comment by illutheplanet** [comment]
it occurs to me:
RuntimeError: Error(s) in loading state_dict for EMANet:
	Unexpected key(s) in state_dict: "extractor.6.0.conv1.weight", "extractor.6.0.bn1.weight", "extractor.6.0.bn1.bias", "extractor.6.0.bn1.running_mean", "extractor.6.0.bn1.running_var", "extractor.6.0.bn1.num_batches_tracked", "extractor.6.0.conv2.weight", "e

**Comment by XiaLiPKU** [comment]
> using the pretrained model throw out this error:
> 
> RuntimeError: Error(s) in loading state_dict for EMANet:
> Missing key(s) in state_dict: "extractor.4.0.conv1.weight", "extractor.4.0.bn1.weight", "extractor.4.0.bn1.bias", "extractor.4.0.bn1.running_mean", "extractor.4.0.bn1.running_var", "extractor.4.0.conv2.weight", ......
> Unexpected key(s) in state_dict: "layer1.0.0.conv1.weight", "layer1.0.0.bn1.weight", "layer1.0.0.b
> 
> someone can help?

Now, I have updated the pretrained model and the link.
You can download it again and direct use it in your code

**Comment by XiaLiPKU** [comment]
> it occurs to me:
> RuntimeError: Error(s) in loading state_dict for EMANet:
> Unexpected key(s) in state_dict: "extractor.6.0.conv1.weight", "extractor.6.0.bn1.weight", "extractor.6.0.bn1.bias", "extractor.6.0.bn1.running_mean", "extractor.6.0.bn1.running_var", "extractor.6.0.bn1.num_batches_tracked", "extractor.6.0.conv2.weight", "e

Now I have updated the pth file. Please download it again.
